=== Informatievlaanderen/OSLOthema-trajectcontrole/schemas/configuration.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/ap-voc-imp.schema.json",
  "title": "OSLO AP-VOC-IMP JSONSchema",
  "description": "JSONSchema voor het valideren van OSLO AP, VOC, IMP configuratiebestanden",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "description": "Naam van de standaard",
        "type": "string"
      },
      "type": {
        "description": "CSS rendering type",
        "type": "string",
        "enum": ["voc", "ap", "impl"]
      },
      "eap": {
        "description": "Enterprise Architect EAP bestandsnaam",
        "type": "string",
        "pattern": ".*\\.eap"
      },
      "diagram": {
        "description": "Het EAP diagram dat bij de standaard hoort",
        "type": "string"
      },
      "template": {
        "description": "Template te gebruiken voor de beschrijvende tekst",
        "type": "string"
      },
      "title": {
        "description": "Titel van de standaard",
        "type": "string"
      },
      "publication-state": {
        "description": "IRI van de StandaardStatus",
        "type": "string",
        "format": "uri"
      },
      "publication-date": {
        "description": "Publicatie datum",
        "type": "string",
        "format": "date"
      },
      "license": {
        "description": "IRI licentie",
        "type": "string",
        "format": "uri"
      },
      "contributors-file": {
        "description": "Contributors' lijst als CSV",
        "type": "string",
        "pattern": ".*\\.csv"
      },
      "contributors-column": {
        "description": "Kolom in CSV die de contributors aangeven",
        "type": "string"
      },
      "site": {
        "description": "Pad naar static files zoals het model in JPG etc.",
        "type": "string"
      },
      "feedbackurl": {
        "description": "GitHub repository URL naar issues tab",
        "type": "string",
        "format": "uri"
      },
      "standaardregisterurl": {
        "description": "URL naar standaard register voor deze standaard",
        "type": "string",
        "format": "uri"
      }
    },
    "required": [
      "name",
      "type",
      "eap",
      "diagram",
      "template",
      "title",
      "publication-state",
      "publication-date",
      "license",
      "contributors-file",
      "contributors-column",
      "feedbackurl",
      "standaardregisterurl"
    ]
  }
}

=== Informatievlaanderen/OSLOthema-trajectcontrole/config/trajectcontrole-voc.json
[
  {
    "name": "trajectcontrole",
    "type": "voc",
    "eap": "OSLO-Trajectcontrole-IMPL.eap",
    "diagram": "OSLO-Trajectcontrole-IM-Enumeraties",
    "template": "trajectcontrole-voc.j2",
    "title": "Vocabularium MAGDA-Voertuigregistrie",
    "publication-state": "https://data.vlaanderen.be/id/concept/StandaardStatus/ZonderStatus",
    "publication-date": "2026-07-23",
    "license": "https://data.vlaanderen.be/id/licentie/modellicentie-gratis-hergebruik/v1.0",
    "contributors-file": "stakeholders.csv",
    "contributors-column": "Rol",
    "site": "site-skeleton/trajectcontrole-im",
    "feedbackurl": "https://github.com/Informatievlaanderen/OSLOthema-trajectcontrole/issues",
    "standaardregisterurl": "https://data.vlaanderen.be/standaarden/vocabularium-magda-voertuigregistratie/"
  }
]

=== Informatievlaanderen/OSLOthema-trajectcontrole/config/trajectcontrole-im.json
[
  {
    "name": "trajectcontrole",
    "type": "impl",
    "eap": "OSLO-Trajectcontrole-IMPL.eap",
    "diagram": "OSLO-Trajectcontrole-IM-Enumeraties",
    "template": "trajectcontrole-im.j2",
    "title": "Implementatiemodel Trajectcontrole",
    "publication-state": "https://data.vlaanderen.be/id/concept/StandaardStatus/ZonderStatus",
    "publication-date": "2026-07-10",
    "license": "https://data.vlaanderen.be/id/licentie/modellicentie-gratis-hergebruik/v1.0",
    "contributors-file": "stakeholders.csv",
    "contributors-column": "Rol",
    "site": "site-skeleton/trajectcontrole-im",
    "feedbackurl": "https://github.com/Informatievlaanderen/OSLOthema-trajectcontrole/issues",
    "standaardregisterurl": "https://data.vlaanderen.be/standaarden/trajectcontrole/"
  }
]

=== Informatievlaanderen/OSLOthema-trajectcontrole/config/voertuigregistraties-im.json
[
  {
    "name": "voertuigregistratie",
    "type": "impl",
    "eap": "OSLO-Voertuigeregistratie-MAGDA-IMPL.eap",
    "diagram": "OSLO-Voertuigregistratie-MAGDA-IM-Enumeraties",
    "template": "voertuigregistratie-im.j2",
    "title": "Implementatiemodel MAGDA-Voertuigregistratie",
    "publication-state": "https://data.vlaanderen.be/id/concept/StandaardStatus/ZonderStatus",
    "publication-date": "2026-07-10",
    "license": "https://data.vlaanderen.be/id/licentie/modellicentie-gratis-hergebruik/v1.0",
    "contributors-file": "stakeholders.csv",
    "contributors-column": "Rol",
    "site": "site-skeleton/voertuigregistratie-im",
    "feedbackurl": "https://github.com/Informatievlaanderen/OSLOthema-voertuigregistratie/issues",
    "standaardregisterurl": "https://data.vlaanderen.be/standaarden/implementatiemodel-voertuigregistratie-magda/"
  }
]

=== Informatievlaanderen/OSLOthema-trajectcontrole/config/voertuigregistraties-voc.json
[
  {
    "name": "voertuigregistratie",
    "type": "voc",
    "eap": "OSLO-Voertuigregistratie-MAGDA-IMPL.eap",
    "diagram": "OSLO-Voertuigeregistratie-MAGDA-IM-Enumeraties",
    "template": "voertuigregistratie-voc.j2",
    "title": "Vocabularium MAGDA-Voertuigregistrie",
    "publication-state": "https://data.vlaanderen.be/id/concept/StandaardStatus/ZonderStatus",
    "publication-date": "2026-07-23",
    "license": "https://data.vlaanderen.be/id/licentie/modellicentie-gratis-hergebruik/v1.0",
    "contributors-file": "stakeholders.csv",
    "contributors-column": "Rol",
    "site": "site-skeleton/voertuigregistratie-im",
    "feedbackurl": "https://github.com/Informatievlaanderen/OSLOthema-voertuigregistratie/issues",
    "standaardregisterurl": "https://data.vlaanderen.be/standaarden/vocabularium-magda-voertuigregistratie/"
  }
]
